import type { Metadata } from "next";
import SocketProvider from "@/providers/SocketProvider";
import "./globals.css";
import { cookies } from "next/headers";
import ClientWrapper from "./client_wrapper";

export const metadata: Metadata = {
  title: "MealBridge Donate",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const donorId = cookieStore.get("donor_id")?.value || null;
  const token = cookieStore.get("token")?.value || null;
  return (
    <html lang="en">
      <body>
        <ClientWrapper donorId={donorId} token={token}>
          <SocketProvider>{children}</SocketProvider>
        </ClientWrapper>
      </body>
    </html>
  );
}
