import type { Metadata } from "next";
import SocketProvider from "@/providers/socket_provider";
import { cookies } from "next/headers";
import ClientWrapper from "../client_wrapper";
import ReactQueryProvider from "@/providers/react_query_provider";
import { Header } from "@layout";

export const metadata: Metadata = {
  title: "MealBridge Donate",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const donorId = cookieStore.get("donor_id")?.value || null;
  const token = cookieStore.get("donor_token")?.value || null;
  return (
    <ClientWrapper donorId={donorId} token={token}>
      <SocketProvider>
        <ReactQueryProvider>
          <Header />
          {children}
        </ReactQueryProvider>
      </SocketProvider>
    </ClientWrapper>
  );
}
